version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_modacad
    restart: always
    ports: 
      - 25060:25060
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: app-modacad
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local